- config/qtsixa.upstream.yaml
- config/sixad.upstream.yaml
Saucy is EOL, so Launchpad won't let me push a release for that. As such, I've left it pulling qtsixa, and added sixad 1.6+ as pulling for trusty and vivid (utopic is also EOL).
More rationale here: https://github.com/ros/rosdistro/pull/9297#issuecomment-138983648
@mikeferguson, @tfoote
> Add importer for sixad 1.6+ from mikepurvis.

- src/reprepro_updater/diff_repos.py
Instead of excluding known endings.
Connects to #21 
Follows Debian Policy Manual definition of versoin 5.6.12: https://www.debian.org/doc/debian-policy/ch-controlfields.html
> Select debian version via positive regex

- config/colladadom.upstream.yaml
is this ok? we have trusty, vivid, wily, we do not have arm deb for saucy and utopic due to they are EOL on launchpad builder.
> added arm debs

- config/catkin_lint.upstream.yaml
By using the `Source` filter, the update rule will continue to function even if binary packages are renamed or removed. Everything built from the `catkin-lint` source package will be matched by the rule.
> Use source package in update rule filter

- config/pyside2.prerelease.lunar.yaml
Fixes #39
I tested the import rule and there's a new version upstream. Here's the dry run of the update: https://gist.github.com/tfoote/3227e3a70406067e77159072b508ce75
@dirk-thomas Running this as is will bring in a new build. Do we want to do so?
> adding pyside2 source entry

- src/reprepro_updater/helpers.py
Based on top of #48.
If any of the invoked subcommands failed (e.g. search for "returned non-zero exit status" in http://build.ros.org:8080/job/import_upstream/125/consoleFull) the script should fail and not "hide" the problem in the hundres of kb of output.
> Fail script in case of failed subcommands

- scripts/include_folder.py
Fixes
https://github.com/ros-infrastructure/buildfarm_deployment/issues/186
> Workaround lack of ddeb support in reprepro

- src/reprepro_updater/helpers.py
- src/reprepro_updater/repository_info.py
I spent time Friday and Saturday trying to investigate the performance issues ticketed in https://github.com/ros-infrastructure/buildfarm_deployment/issues/165
My main test case is rebuilding catkin on indigo trusty amd64
My test farm isn't quite the same as the production farm. It's a little under-powered but that makes it easier to test the impact of performance improvements.
With a fresh import of indigo from the production repositories the first catkin import package job takes ~2.5 hours. Which is enough to make the catkin build job timeout and require a second run to complete successfully. Since the import package job does clean out the repositories, subsequent package imports complete within normal range because everything must be rebuilt.
Since we had fewer issues with the same …
> Improve performance of include_folder.py

- scripts/include_folder.py
Reprepro doesn't support *.ddeb files (https://github.com/ros-infrastructure/buildfarm_deployment/issues/186). We've worked around this up until now by removing ddeb entries from the .changes file #55 before importing packages.
However this means that we don't have accessible debug symbols for melodic on artful and bionic.
Empirical testing shows that these "ddeb" packages are pretty much just .debs with a funny file extension. Changing the name doesn't prevent the package from being installed and the dbgsym packages in Debian Stretch (which our buildfarm already has and supports) are just regular .deb packages.
So with this change, instead of just dropping the ddebs from a changes file we rename them to deb and use the changes manifest to find and rename the ddeb files on disk before …
> Rename incoming ddeb files

- config/gazebo9_ubuntu_bionic.ppa.yaml
Custom build of gazebo 9.0.0 (version in Bionic repos) with a minimal patch to include static libraries.
Details in the SRU bug:
https://bugs.launchpad.net/ubuntu/+source/gazebo/+bug/1773811
> Import custom gazebo9 for Bionic to solve problems with missing test_fixture lib

- config/opensplice69.osrfoundation.yaml
FYI @tfoote and @dirk-thomas I'm merging this to use it.
Imports packages built by https://build.osrfoundation.org/job/opensplice-debbuilder/ and supersedes the existing configuration in the ROS 2 buildfarm_deployment_config.
> Add config for importing libopensplice69.

- scripts/sync_ros_packages.py
This doesn't change behavior, source diffs are already omitted because they lack Packages files. This change prints a message that does not contain the word "Exception" before continuing with the sync.
> Skip source architecture before error is raised.

- scripts/sync_ros_packages.py
Follow up from #65 which resolves the problem of source packages not being synchronized.
Thanks to @clalancette for reporting the issue.
> Add source to updates_generator before continuing.

- config/lark-parser.osrfoundation.yaml
The deb is built and present here http://packages.osrfoundation.org/gazebo/debian-stable/pool/main/l/lark-parser/
> Import lark-parser into stretch as well as xenial and bionic.

- config/lark-parser.debian.osrfoundation.yaml
The ubuntu-stable and debian-stable repositories on packages.osrfoundation.org are not mutual symlinks.
This effectively reverts #67 and replaces it with a separate config that pulls the Debian package for Stretch from the debian-stable repo. To update lark-parser in the future both configs will need to be run.
This config was hand deployed and run on the build farm to produce http://build.ros2.org/job/import_upstream/165/
> Fix lark-parser import on Debian Stretch

- config/pycryptodome.yaml
- src/reprepro_updater/conf.py
This will pull in python-pycryptodome, python3-pycryptodome, and python-pycryptodome-doc. Only the first is strictly necessary but I feel like it makes more sense to grab the full set.
To enable this to work I had to re-introduce support for the source_suite option which appears to have been removed in the refactor branch (or was added to master and not propagated, I have not done the spelunking to find out).
I dry-ran this using a local checkout on a repository host and it would have added the following packages:
```
add 'python-pycryptodome' - '3.4.7-1~bpo9+1' 'pycryptodome'
add 'python-pycryptodome-doc' - '3.4.7-1~bpo9+1' 'pycryptodome'
add 'python3-pycryptodome' - '3.4.7-1~bpo9+1' 'pycryptodome'
add 'python-pycryptodome' - '3.4.7-1~bpo9+1' 'pycryptodome'
add 'python-pycryptodome-doc' …
```
> Add config for importing pycryptodome and reintroduce source_suite option

- scripts/include_folder.py
Fixes #73 
According to the RFC it's mandatory but it's been moved away from for source only packages.
Signed-off-by: Tully Foote <tfoote@osrfoundation.org>
> Avoid reading Binary section if in a source changes file.

- config/gazebo11_debian_buster.yaml
- config/gazebo11_ubuntu_focal.yaml
For both, Noetic (ROS1) and Foxy (ROS2) we need to import gazebo11 packages together with all its dependencies. I added two files here to import all the needed files from packages.osrfoundation.org. 
Some packages are affected by https://github.com/ignition-tooling/release-tools/issues/186 and don't have -dbg packages. I think this should not stop us from starting the upload in order to unblock the `gazebo_ros_pkgs` porting, testing and release.
/cc @chapulina
> Add gazebo11 Debian Buster and Ubuntu Focal

- scripts/sync_ros_packages.py
Seems like python was having bad time with some characters in print command, probably coming from `Steven! Ragnarök` ;) . I forced the encode to utf8. The job displays the diff:
```
14:25:03 Difference between 'file:///var/repos/ubuntu/testing/dists/bionic/main/binary-amd64/Packages' and 'file:///var/repos/ubuntu/building/dists/bionic/main/binary-amd64/Packages' computed at 2020-10-29-13:25:03
14:25:03 --------------------------------------------------------------------------------
14:25:03 ## Package Updates for eloquent
14:25:03 
14:25:03 ### Added Packages [3]:
14:25:03 
14:25:03  * ros-eloquent-ament-cmake-core: 0.8.2-1
14:25:03  * ros-eloquent-ament-package: 0.8.9-1
14:25:03  * ros-eloquent-ros-workspace: 1.0.1-1
14:25:03 
14:25:03 ### Updated Packages [0]:
14:25:03 
14:25:03 …
```
> Encode announcement print statement

- scripts/diff_packages.py
- scripts/sync_ros_packages.py
- src/reprepro_updater/diff_repos.py
- test/test_diff.py
`PackageFile` constructor:
```python
def __init__(self, name, file_obj=None, encoding="utf-8"):
"""Creates a new package file object.
name - the name of the file the data comes from
file_obj - an alternate data source; the default is to open the
file with the indicated name.
"""
if file_obj is None:
file_obj = open(name, 'rb')
```
and iter as:
```python
def __iter__(self):
line = self.file.readline().decode(self.encoding)
```
When using `StringIO` the readline returns `str` and the decode fails. When using real filesystem paths, the readline returns `bytes` and the thing seems to work fine.
Upstream code could be patched to work with `StringIO` I'll see if I have time to send a patch there.
Tested here:
[![Build Status](https://build.test.ros2.org/buildStatus/icon?job=Erel_sync-packages-to …
> Use NamedTemporaryFile to avoid problems with PackageFile+StringIO in python3

- config/vcstool.debian.upstream.yaml
- config/vcstool.ubuntu.upstream.yaml
To configure the import from the `vcstool` upstream repo https://packagecloud.io/dirk-thomas/vcstool.
This config only contains the Python 2 packages. I intend to do one last Python 2 release directly into the ROS apt repos adding a message that this is the last Python 2 release and users should update to Python 3 packages.
> add vcstool upstream config

- scripts/sync_ros_packages.py
For python3 encoding the string returns a bytes object rather than a
string rather than a correctly encoded string. The regression was introduced when the switch to python3 was completed with https://github.com/ros-infrastructure/ros_buildfarm/pull/842
Printed announcement before:
```
--------------------------------------------------------------------------------
09:46:10 b'## Package Updates for dashing\n\n### Added Packages [0]:\n\n\n### Updated Packages [0]:\n\n\n### Removed Packages [0]:\n\n\nThanks to all ROS maintainers who make packages available to the ROS community. The above list of packages was made possible by the work of the following maintainers: \n\n'
09:46:10 --------------------------------------------------------------------------------
```
and after
``` 
09:47:56 …
```
> Handle differences between Python 2 and 3.

- config/pyside2.prerelease.yaml
Because the source package for the pyside2 collection is called simply `pyside2` it was not imported as was originally intended along with the rest of these packages. Because the source package for shiboken2 is called `shiboken2` that source package was successfully imported previously.
The version of pyside2 which was imported previously is no longer available in the linked PPA so this import should not be re-run unless the PPA is updated or an examination of the differences between the current ROS and PPA packages is performed.
> Add the pyside2 source package to the import formula.

- config/lark-parser_xenial.yaml
The formula will import the lark-parser packages (including source package) corresponding to the rebuild effort of the same source used in http://repos.ros.org/repos/ros_bootstrap/pool/main/l/lark-parser/ to recreate the source package file for version `0.7.2-1`.
Revision number has been bumped to `0.7.2-2`.
I ran the debdiff tool on both packages and try to run auto-abi checker: https://github.com/j-rivero/bootstrap_abi_checking/runs/1971577269?check_suite_focus=true
debdiff tool is reporting:
```
021-02-24T15:54:02.6022565Z #16 0.263 prep_p: prerelease/python3-lark-parser_0.7.2-1osrf~xenial_all.deb
2021-02-24T15:54:02.6023305Z #16 0.265 
2021-02-24T15:54:02.6023951Z #16 0.266 ************************
2021-02-24T15:54:02.6025494Z #16 0.266 COMPARING …
```
> Add lark-parser source package import formula (Xenial)

- config/ceres_xenial.yaml
The formula will import the ceres-solver packages (including source package) corresponding to the rebuild effort of the same source used in http://repos.ros.org/repos/ros_bootstrap/pool/main/c/ceres-solver/ to recreate the source package file for version `1.12.0+dfsg0-1~ubuntu16.04.1`, revision has changed to `libceres1_1.12.0+dfsg0-5_amd64.deb `, source code should be the same.
I ran the debdiff tool on both packages and try to run auto-abi checker: https://github.com/j-rivero/bootstrap_abi_checking/runs/1990550634?check_suite_focus=true
debdiff + abipkgdiff tools are happy, reporting:
```
2021-02-26T20:39:22.4052848Z #17 0.357 ************************
2021-02-26T20:39:22.4053990Z #17 0.357 COMPARING DEBDIFF bootstrap/libceres1_1.12.0+dfsg0-1~ubuntu16.04.1_amd64.deb -- …
```
> Add ceres-solver source package import formula (Xenial)

- config/pytest-runner_ubuntu_xenial.ppa.yaml
The formula will import the pytest-runner packages (including source package) corresponding to the rebuild effort of the same source used in http://repos.ros.org/repos/ros_bootstrap/pool/main/p/pytest-runner/ to recreate the source package file for version `2.11.1-1`, revision has changed to `2.11.1-3 `, source code should be the same.
I ran the debdiff tool on both packages and try to run auto-abi checker: https://github.com/j-rivero/bootstrap_abi_checking/actions/runs/610821370
debdiff + abipkgdiff tools are happy, although there is a changelog file reported to be new in the new packages:
```
2021-03-01T14:43:13.7151210Z #17 0.283 ************************
2021-03-01T14:43:13.7152359Z #17 0.283 COMPARING DEBDIFF bootstrap/python3-pytest-runner_2.11.1-1_all.deb -- …
```
> Add pytest-runner source package import formula (Xenial)

- config/lark-parser_stretch_buster.yaml
- config/lark-parser_xenial.yaml
- config/lark-parser_xenial_bionic.yaml
When importing the new source package for Xenial it introduced a conflict with the already-present source package orig.tar files so we've updated all of them to use the same one.
> Converge lark-parser packages on a single orig.tar for 0.7.2

- config/ignition_citadel_gazebo11_ubuntu_focal.yaml
New versions of ign-gui3 and ign-msgs5 appeared while we were processing #102 . This PR list and updates to latest version them.
> Update gui3 and msgs5 in ignition_citadel_gazebo11_ubuntu_focal to latest version

- config/ignition_citadel_gazebo11_debian_buster.yaml
- config/ignition_citadel_gazebo11_ubuntu_focal.yaml
- config/ignition_edifice_debian_buster.yaml
- config/ignition_edifice_ubuntu_focal.yaml
Focal imports failed after https://github.com/ros-infrastructure/reprepro-updater/pull/111
Compared to the Buster filters, Focal was missing a lot of sub-packages. I had assumed there was some globbing going on, but that doesn't seem to be the case.
This PR makes Focal and Buster as similar as they can be by using `*` for the distro name. This should make it easier to compare them:
```.diff
$ diff -u config/ignition_edifice_debian_buster.yaml config/ignition_edifice_ubuntu_focal.yaml 
--- config/ignition_edifice_debian_buster.yaml	2021-05-04 16:39:32.060849643 -0700
+++ config/ignition_edifice_ubuntu_focal.yaml	2021-05-04 16:39:11.708572984 -0700
@@ -1,8 +1,8 @@
-name: ignition_edifice_debian_buster
-method: http://packages.osrfoundation.org/gazebo/debian-stable
-suites: [buster]
+name: …
```
> Ignition: fix Focal

- config/ignition_citadel_gazebo11_debian_buster.yaml
- config/ignition_citadel_gazebo11_ubuntu_focal.yaml
Follow-up to https://github.com/ros-infrastructure/reprepro-updater/pull/112
It's still failing to install `ignition-edifice` on Focal:
```
The following packages have unmet dependencies:
ignition-edifice : Depends: libignition-cmake2-dev (>= 2.7.0) but 2.6.2-1~focal is to be installed
Depends: libignition-common4-dev but it is not going to be installed
Depends: libignition-fuel-tools6-dev but it is not going to be installed
Depends: libignition-gazebo5-dev but it is not going to be installed
Depends: libignition-gui5-dev but it is not going to be installed
Depends: libignition-launch4-dev but it is not going to be installed
Depends: libignition-math6-dev (>= 6.8.0) but 6.7.0-1~focal is to be installed
Depends: libignition-math6-eigen3-dev (>= 6.8.0) but it is not going to be installed …
```
> Ignition: bump ign-cmake2 and gazebo11 and add ignition-fuel-tools to Buster.

- config/ignition_citadel_gazebo11_debian_buster.yaml
- config/ignition_citadel_gazebo11_ubuntu_focal.yaml
Because of this typo, any version of ignition-cmake2/libignition-cmake2
was being installed as well as any package with a version 2.7.0-1~*.
> Fix typo in filter formula.

- config/ignition_citadel_gazebo11_debian_buster.yaml
- config/ignition_citadel_gazebo11_ubuntu_focal.yaml
- config/ignition_edifice_debian_buster.yaml
https://github.com/ros-infrastructure/reprepro-updater/pull/111 introduced a bug by removing `gazebo11-plugin-base`. This PR should fix it.
PR and sync will address https://github.com/osrf/gazebo/issues/2995
> Missing gazebo11-plugin-base from #111

- config/ignition_citadel_gazebo11_debian_buster.yaml
- config/ignition_citadel_gazebo11_ubuntu_focal.yaml
- config/ignition_edifice_debian_buster.yaml
Still trying to settle on installable gazebo and ignition packages. I used some ad-hoc automation to grab the current versions from the Gazebo repositories and check that against what we had configured.
Shell scripts are in Fish so be sure to translate them to their POSIX equivalents
Grab the Sources manifests from the OSRF repostiories, I make the assumption that all binary packages we need to import are present in the configs and that all binary packages matching the source package versions are present in the OSRF repos.
```fish
curl 'http://packages.osrfoundation.org/gazebo/debian-stable/dists/buster/main/source/Sources.gz' | zcat > debian-buster-sources
curl 'http://packages.osrfoundation.org/gazebo/ubuntu-stable/dists/focal/main/source/Sources.gz' | zcat > ubuntu-focal-sources
```
I …
> Update package versions to latest.

- .github/workflows/ci.yml
Key import from gnupg.net is failing in #120.
> Use Ubuntu keyserver in CI workflows.

- config/catkin_lint.upstream.yaml
This will also remove Xenial (it's EOL and will no longer be updated in my PPA) and fix a bug in the FilterFormula that prevented propagation of all binary packages (`$Source` instead of `Source` is needed).
> Bump catkin_lint to 1.6.14

- .github/workflows/ci.yml
This is pretty brittle in general, I wonder if we can trust a top level
key or import all Debian keys as we do with the Ubuntu keys (which is
easy because we're running the CI on Ubuntu.)
> Add bullseye key to test scripts.

- config/vcstool.debian.upstream.yaml
- config/vcstool.ubuntu.upstream.yaml
`vcstool` version dropped support for Python 2.7 and 3.4 hence the removal of `jessie`.
> bump vcstool to 0.3.0

- config/ignition_citadel_gazebo11_debian_buster.yaml
- config/ignition_citadel_gazebo11_ubuntu_focal.yaml
Periodic update to the latest versions.
I'd like to get this in before #128 , to reduce that PR
> Update Gazebo 11 and Ignition Citadel

- config/ignition_edifice_debian_buster.yaml
- config/ignition_edifice_ubuntu_focal.yaml
Similar to #129, periodic update to the latest versions.
I'd like to get this in before #128 , to reduce that PR
One thing I did differently here was to remove the revision `-1` from the versions, because some packages were released as `-2`
> Upgrade Ignition Edifice packages

- config/ignition_edifice_debian_buster.yaml
- config/ignition_edifice_ubuntu_focal.yaml
Caused by https://github.com/ros-infrastructure/reprepro-updater/issues/133 to complete #131. 
Reviewing the dependencies manually I did not find other missing pieces.
> Missing libignition-physics4-heightmap-dev for edifice

- config/ignition_citadel_gazebo11_debian_buster.yaml
Most Ignition packages are available for those architectures, so it would be nice to import them here.
This is meant to fix https://github.com/ignitionrobotics/ros_ign/issues/173
As a reference, here are the current packages available on packages.osrfoundation.org, generated with [this script](https://github.com/ignition-tooling/release-tools/blob/master/terminal-dashboard/table.bash):
<details><summary>As text</summary>
<p>
```
ignition-cmake2
bionic   amd64    2.9.0-1    i386     2.9.0-1    arm64    2.9.0-1    armhf    2.9.0-1   
focal    amd64    2.9.0-1    i386     disabled   arm64    2.9.0-1    armhf    2.9.0-1   
buster   amd64    2.9.0-1    i386     2.9.0-1    arm64    2.9.0-1    armhf    2.9.0-1   
ignition-math6
bionic   amd64    6.9.2-1    i386     6.9.2-1    arm64    6.9.2-1 …
```
> Ignition Citadel: Buster i386, armhf and arm64

- scripts/aptly/aptly_importer_TEST.py
- scripts/aptly/test/example.yaml
It appears that groovy is no longer on archive.ubuntu.com.
> Target Jammy in place of EOL Groovy in scripts

- config/ignition_fortress_debian_buster.yaml
- config/ignition_fortress_ubuntu_focal.yaml
* Follow up to #128 , it's currently not possible to install `ignition-fortress` just with packages.ros.org
I copied what we have for Ogre 2.1 on Citadel:
https://github.com/ros-infrastructure/reprepro-updater/blob/78a5edd2dad41479dcc3ead254eb6db2dc7bbd9f/config/ignition_citadel_gazebo11_ubuntu_focal.yaml#L126-L129
These are the versions we have on packages.osrfoundation.org
```
libogre-2.2-dev/unknown,now 2.2.5+20210824~ec3f70c-4osrf~focal amd64 [installed]
libogre-2.2/unknown,now 2.2.5+20210824~ec3f70c-4osrf~focal amd64 [installed,automatic]
ogre-2.2-doc/unknown,unknown 2.2.5+20210824~ec3f70c-4osrf~focal all
ogre-2.2-tools/unknown 2.2.5+20210824~ec3f70c-4osrf~focal amd64
```
> Add Ogre 2.2 (For Ignition Fortress)

- .github/workflows/ci.yml
Fetch via https rather than the keyserver network since the key appears to've changed since we last updated these scripts and this makes it robust to those changes as long as the aptly devs keep updating their https-hosted public key. Also, we've seen that the keyserver network is crumbling and this will probably be more reliable in general.
> Update aptly key

- config/ignition_edifice_ubuntu_focal.yaml
This supersedes #145 which updates version numbers but does not actually match the current packages in the packages.osrfoundation.org repository.
The first commit on this PR, a3e52e855b395165396950a71180577a384e7d35 updates the format of the config file while not changing any contents so that it's easier to diff between the updated, generated content, and the previous content.
I recommend that reviewers use custom compare links to review the changes without formatting differences.
* [ubuntu_focal](https://github.com/ros-infrastructure/reprepro-updater/compare/dcacc2424401911524a379ed909b328d8f5755c5..nuclearsandwich/edifice-updates-2022-04-05#diff-9f768fbe2a06da79aae35728f17b7c509b43ed450effff17065caae1d7956a74)
* [debian_buster](https://github.com/ros-infrastructure/reprepro-updater/compa …
> Update Ignition Edifice packages using generator script.

- .github/workflows/ci.yml
I kept hitting https://github.com/jitterbit/get-changed-files/issues/42 when working on recent PRs. So I decided to see what it would take to get my own approach in.
The answer, it turned out was not much in terms of trickery but a fair bit of tweaking to account for the GitHub actions environment. I am in favor of this "just use git" but it does mean fetching a deep clone rather than a shallow one. For this project that shouldn't be too punishing though.
> Implement my own file change detection.

- config/ignition_fortress_ubuntu_jammy.yaml
According to the script which scraped packages.osrfoundation.org ogre-2.2 is missing. I know there were plans to make an ogre-next package available upstream in Ubuntu Jammy but I don't think those plans have progressed.
Created using the script in #144
> Update Fortress packages for Ubuntu Jammy.

- .github/workflows/ci.yml
- config/ignition_citadel_gazebo11_debian_buster.yaml
- config/ignition_citadel_gazebo11_ubuntu_focal.yaml
Uses the script from #144 
[comparison url using the commit after reformatting](https://github.com/ros-infrastructure/reprepro-updater/compare/55f6aaffef2f0cb1379e6320eabe4b11ecca87a8..nuclearsandwich/citadel-update-2022-04-14)
> Update Citadel imports for Ubuntu Focal.

- config/colcon.ubuntu.upstream.yaml
We noticed while debugging other issues that the Jammy repositories actually still include colcon-core 0.6.1.
> Drop xenial and add jammy from import suites.

- config/ignition_fortress_ubuntu_jammy.yaml
Fixes: https://github.com/gazebo-release/gz-math6-release/issues/11
> Import ign-cmake 2.12.1-2 and ign-math 6.11.0-3 to install Gazebo11 and RVIZ on Jammy

- config/ignition_fortress_ubuntu_jammy.yaml
Using the current generator script from #144.
The primary objective of this update, although it is not reflected in the config. Is to pull in arm64 packages for Fortress now that they are available. I'll post the bootstrap snapshot diff after import to verify that they were pulled in before running import jobs.
> Update Fortress config for Ubuntu Jammy.

- config/ignition_fortress_ubuntu_jammy.yaml
Follow up problems with dependencies after #152 and #165. I'm pretty sure that we need common4, msgs8 and sensors bumps to make the whole fortress collection to install.
> Update for Fortress: common, gui, msgs, physics and plugin

- config/ignition_fortress_ubuntu_jammy.yaml
Almost there. Following #166
```
The following packages have unmet dependencies:
libignition-gazebo6 : Depends: libignition-sensors6-boundingbox-camera (>= 6.6.0) but it is not installable
libignition-gazebo6-plugins : Depends: libignition-sensors6-boundingbox-camera (>= 6.6.0) but it is not installable
libignition-sensors6-dev : Depends: libignition-sensors6-boundingbox-camera-dev (= 6.6.0-2~jammy) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
> Fortress missing boundingbox-camera package

- config/ignition_citadel_gazebo11_ubuntu_focal.yaml
- config/ignition_fortress_ubuntu_focal.yaml
* Part of https://github.com/gazebo-tooling/release-tools/issues/788
Summary:
* Add all `gz` counterparts to `ignition` packages
* Bump to the latest releases. ⚠️ I've included some versions that are staged to be released, but not there yet:
* Also removed libraries from Fortress that are duplicates of Citadel, only for Focal. I think it makes sense to have a single source of truth.
* I didn't update Buster on purpose, because that's EOL and we haven't been making new releases for it
Here's the current status of Citadel source packages on packages.osrf (this doesn't check that the `gz` packages exist, I've done that manually 🙃 ):
> Import Citadel gz packages

- config/ignition_citadel_gazebo11_ubuntu_focal.yaml
- config/ignition_fortress_ubuntu_focal.yaml
- config/ignition_fortress_ubuntu_jammy.yaml
* Builds on top of https://github.com/ros-infrastructure/reprepro-updater/pull/168
* Part of https://github.com/gazebo-tooling/release-tools/issues/788
Summary:
* Add all `gz` counterparts to `ignition` packages
* Bump to the latest releases. ⚠️ I've included some versions that are staged to be released, but not there yet:
* I didn't update Buster on purpose, because that's EOL and we haven't been making new releases for it
Here's the current status of Fortress source packages on packages.osrf (this doesn't check that the `gz` packages exist, I've done that manually 🙃 ):
> Import Fortress gz packages

- config/colcon.debian.upstream.yaml
- config/colcon.ubuntu.upstream.yaml
Assuming that everything worked colcon-meson 0.4.2 is now available in the colcon apt repositories for us to import.
The package only currently supports Ubuntu Jammy due to the meson >= 0.6 requirement.
> Add colcon-meson package to colcon imports.

- config/colcon.debian.upstream.yaml
- config/colcon.ubuntu.upstream.yaml
Imported here: https://packagecloud.io/dirk-thomas/colcon
This package only targets Jammy and Bullseye due to dependency availability.
> Add colcon-clean package

- .github/workflows/ci.yml
Bionic is EOL and the GitHub job deprecated. This pr updates the job to the next Ubuntu LTS, Focal.
> Update aptly import CI to Focal

- config/ignition_fortress_ubuntu_focal.yaml
- config/ignition_fortress_ubuntu_jammy.yaml
Prepare the sync of all Gazebo Fortress latest versions in packages.o.o corresponding to Ubuntu Jammy and Ubuntu Focal.
> Update all Fortress versions to latest in Focal/Jammy

- config/ignition_fortress_ubuntu_focal.yaml
- config/ignition_fortress_ubuntu_jammy.yaml
New parameters packages from transport11 were missing in #182
> Missing Fortress transport11 new packages in #182

- config/colcon.debian.upstream.yaml
- config/colcon.ubuntu.upstream.yaml
Imported here: https://packagecloud.io/dirk-thomas/colcon
* colcon-alias 0.1.0
* colcon-bash 0.5.0
* colcon-core 0.13.0
* colcon-devtools 0.2.4
* colcon-parallel-executor 0.3.0
* colcon-recursive-crawl 0.2.2
* colcon-rerun 0.1.0
* colcon-ros 0.4.0
> Update several colcon package versions

- .github/workflows/ci.yml
Two high-level changes here:
* Drop the matrix in favor of conditionally running steps
The job runs so fast that I don't think there's any advantage in parallelizing using the matrix
* Use base ref SHA for determining which files changed
The intent here is to make PRs from forks work by not referencing `origin`.
> Rework some sharp edges in GitHub Actions

- config/packages.osrfoundation.org/dart6.13_gazebo_noble.ppa.yaml
Dart 6.13.1 packages are ready for Noble in the usual PPA. 
However 6.13.1 is blocked in https://github.com/gazebosim/gz-physics/issues/586 on Jammy waiting to solve some problems found during testing. I have split the import configuration in two files in this PR to handle Noble and Jammy separately.
@azeey how far are we of getting the 6.13.1 support ready?
> Added dart 6.13.1 import for Noble

- doc/deploying_ros_bootstrap_repo_imports.md
First draft of ros_bootstrap repo deployment docs.
> Add docs for deploying to the ROS bootstrap repo.

- config/ignition_citadel_gazebo11_ubuntu_focal.yaml
Part of https://github.com/gazebo-tooling/release-tools/issues/1223
Citadel has reached EOL and this is the final sync.
<details><summary>Packages in packages.osrfoundation.org and packages.ros.org</summary>
<p>
This was generated using
```
grep -oP "(?<=Package \(= ).*(?=\))" config/ignition_citadel_gazebo11_ubuntu_focal.yaml | xargs apt-cache madison | v
```
and filtered manually to only keep the main `-dev` packages.
```
ignition-citadel | 1.0.2-2~focal | http://packages.osrfoundation.org/gazebo/ubuntu-stable focal/main amd64 Packages
ignition-citadel | 1.0.2-2~focal | http://packages.ros.org/ros2/ubuntu focal/main amd64 Packages
libignition-cmake2-dev | 2.17.2-1~focal | http://packages.osrfoundation.org/gazebo/ubuntu-stable focal/main amd64 Packages
libignition-cmake2-dev | …
```
> Import Gazebo11 11.15.0 and sync Citadel packages for Focal

- config/ignition_citadel_gazebo11_ubuntu_focal.yaml
reprepro does not handle correctly our conditional groups  formed by `( (Package | Package | Package) AND Version )`. I modified them to add an extra parenthesis around the whole group and the things seems to work now:
https://build.ros.org/job/import_upstream/332/consoleFull
The sed command is: `sed -i -e 's/(Package/\((Package/' -e 's/Version \(.*\))/Version \1))/'`
> Fix reprepro filter in Citadel Gazebo11 file

- config/ignition_citadel_gazebo11_ubuntu_focal.yaml
How did I get the value for the verify_release that is a bit special:
```
wget https://packages.osrfoundation.org/gazebo/ubuntu-stable/dists/focal/Release.gpg
gpg --list-packets Release.gpg 
:signature packet: algo 1, keyid 67170598AF249743
version 4, created 1733241503, md5len 0, sigclass 0x00
digest algo 10, begin of digest a8 86
hashed subpkt 33 len 21 (issuer fpr v4 D2486D2DD83DB69272AFE98867170598AF249743)
hashed subpkt 2 len 4 (sig created 2024-12-03)
subpkt 16 len 8 (issuer key
```
Seem to match the last 16 chars of the long key id:
```
❯ gpg --list-keys | grep -2 67170598AF249743
pub   rsa2048 2015-04-01 [SC]
D2486D2DD83DB69272AFE98867170598AF249743
uid           [ unknown] OSRF Repository (OSRF Repository GPG key) <osrfbuild@osrfoundation.org>
sub   rsa2048 2015-04-01 [E]
```
It …
> Add packages.o.o verify key to ignition_citadel_gazebo11_ubuntu_focal

- config/ignition_citadel_gazebo11_ubuntu_focal.yaml
Related to https://github.com/gazebosim/gazebo-classic/issues/3416
Some release versions do not match the Packages file in the focal directory, particularly msgs5 and transport8. Used this changed locally to run an import upstream dry-run and the log displays the output of both packages: https://build.ros.org/job/import_upstream/335/consoleFull.
> Fix Citadel upload for msgs5 and transport8

- src/reprepro_updater/conf.py
- src/reprepro_updater/repository_info.py
Fixes:
* Deprecated SafeConfigParser usage. Replaced with ConfigParser
* SyntaxWarning of empty string comparison
> 24.04 migration

- scripts/import_upstream.py
import_upstream job is failing in python 3.12 because yaml.load needs a Loader param:
```
00:00:04.898 loading config file: /home/jenkins-agent/reprepro_config/ros_bootstrap.yaml
00:00:05.000 Traceback (most recent call last):
00:00:05.000   File "/home/jenkins-agent/workspace/import_upstream/reprepro-updater/scripts/import_upstream.py", line 49, in <module>
00:00:05.000     yaml_dict = yaml.load(fh.read())
```
> Use yaml.safe_load instead of yaml.load
