src/reprepro_updater/helpers.py

FIxes #2 
New version: http://build.ros.org:8080/job/Irel_import-package/15575/console recursively removing all downstream
Old version: http://build.ros.org:8080/job/Irel_import-package/10771/console removing declared dependencies only

Make invalidation be recursive

---

config/colladadom.upstream.yaml

See: https://github.com/ros/rosdistro/issues/9945#issuecomment-194642340

add wily to suites to import for collada-dom

---

config/pyside2.prerelease.yaml

Related to ros/rosdistro#10940

add pyside2 import rules

---

config/pyside2.prerelease.yaml

See https://launchpad.net/~thopiekar/+archive/ubuntu/pyside-git/+packages
@tfoote Please run the import after merging this.

add armhf and arm64 packages of PySide 2 / Shiboken 2

---

src/reprepro_updater/diff_repos.py

This will make life easier when copying and pasting.

update the generated diff to be properly formatted markdown

---

config/catkin_lint.upstream.yaml

Looks like there are no builds for zesty [on the ppa](http://ppa.launchpad.net/roehling/latest/ubuntu/pool/main/c/catkin-lint/) at the moment so I'm adding only yakkety. Is this the way to go or should I add zesty too and it will just start working once the deb is available ?

add catkin-lint yakkety

---

config/gazebo8_debian.upstream.yaml
config/gazebo8_ubuntu.upstream.yaml

Re: https://github.com/ros/rosdistro/pull/15000#issuecomment-303245812
@j-rivero @mikaelarguedas

removing gazebo8 imports now that they've been rolled back.

---

remove_packages.py
scripts/diff_packages.py
scripts/import_upstream.py
scripts/include_folder.py
scripts/setup_repo.py
scripts/sync_ros_packages.py
src/reprepro_updater/changes_parsing.py
src/reprepro_updater/conf.py
src/reprepro_updater/diff_repos.py
src/reprepro_updater/helpers.py
test/test_diff.py
test/test_generate_incoming.py

Since I need to make a couple of bug fixes to this package I first cleaned up the code in order to stay sane when trying to edit the code. First the code should use valid Python 3 syntax, second it should comply with standard Python linters.

fix syntax to be Python 3 compatible, fix various style warnings

---

src/reprepro_updater/conf.py

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

Add in bionic to the list of distros.

---

src/reprepro_updater/diff_repos.py

Add homepage link to changelog summary.

---

config/pyside2.prerelease.lunar.yaml

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

Add bionic to the list for pyside2.

---

config/lark-parser.osrfoundation.yaml

As requested on https://github.com/ros2/ros2/issues/638#issuecomment-456473404.

add xenial for lark-parser import

---

config/catkin_lint.upstream.yaml

Per discussion in https://github.com/ros/rosdistro/issues/24251

Update catkin_lint upstream to new PPA

---

config/colcon.debian.upstream.yaml
config/colcon.ubuntu.upstream.yaml

@nuclearsandwich Please merge and import after reviewing. Thanks.

bump colcon-ros to 0.3.21

---

config/gazebo9_bionic.yaml

The formula will import the gazebo source package corresponding to the packages in http://repos.ros.org/repos/ros_bootstrap/pool/main/g/gazebo/.
There is an ancient 1.9 source package named gazebo there that can be overwritten safely since all versions using it are EOL.

Add gazebo9 source package import formula (Bionic)

---

config/ignition_edifice_debian_buster.yaml

We might think about dropping the distribution for a glob in the future.

Update distribution in version string.

---

config/packages.osrfoundation.org/openrobotics_dart_packages_from_ppa.yaml

Set 6.10.0~osrf19~20210610~bionic~175596b511adb55d831c0c3401ef50e2cb96a6f3 version for dart

---

config/ignition_fortress_ubuntu_focal.yaml

Update Fortress packages in Ubuntu Focal

---

config/colcon.debian.upstream.yaml
config/colcon.ubuntu.upstream.yaml

Imported to: https://packagecloud.io/dirk-thomas/colcon

Add colcon-hardware-acceleration

---

config/ignition_citadel_gazebo11_ubuntu_focal.yaml

Mainly to get arm64 versions for ignition-gazebo3 to help with https://github.com/gazebosim/ros_gz/issues/173

Update citadel on focal for ignition-gazebo3

---

config/ignition_fortress_ubuntu_jammy.yaml

Probably fixes https://github.com/gazebosim/gz-cmake/issues/304

Update fortress jammy: ign-cmake, rendering and gazebo6

---

config/ignition_citadel_gazebo11_ubuntu_focal.yaml
config/ignition_fortress_ubuntu_focal.yaml

Trying to wrap up https://github.com/ros/rosdistro/pull/34177.
This import should resolve the current failure to find `libgz-utils1-dev`.

Update ubuntu focal config for fortress.

---

src/reprepro_updater/helpers.py

This is a kick-off PR since I am flying today. There are plenty of valid ways to break this one down. I was planning to try 1 partition, then 2, then 4, and so on. One challenge is that package names are not all the same length so it is possible that in two partitions the first may be small enough but the second would not so all partitions have to be templated as commands and checked before running any.
Since we already have a fully enumerated set of packages to invalidate I don't think there is any ordering requirement of which packages we remove in which order so long as the overall operation only reports success if all commands succeed.

Handle removefilter args that exceed command line max length.

---

config/colcon.debian.upstream.yaml
config/colcon.ubuntu.upstream.yaml

This matches what all future releases of colcon packages are expected to support.

Update target platforms for colcon upstream repos

---

config/ignition_fortress_ubuntu_focal.yaml
config/ignition_fortress_ubuntu_jammy.yaml

Small sync for Gazebo Fortress packages, requested by @azeey

Sync Fortress packages for Jammy and Focal

---

config/packages.osrfoundation.org/dart6.13_gazebo_ppa.yaml

Part of https://github.com/gazebosim/gz-physics/issues/586

Bump DART Gazebo ppa to 6.13.1

---

config/packages.osrfoundation.org/dart6.13_gazebo_ppa.yaml

Include Noble in Gazebo DART ppa file 6.13

---

config/packages.osrfoundation.org/dart6.13_gazebo_ppa.yaml

Both ready in the PPA https://launchpad.net/~openrobotics/+archive/ubuntu/dart6.13-gazebo

Bump DART version to 6.13.2

---

config/packages.osrfoundation.org/dart6.13_gazebo_ppa.yaml

Follow up #209 
Testing https://build.osrfoundation.org/job/reprepro_importer/134/console

Use wildcard operator

---

config/colcon.debian.upstream.yaml
config/colcon.ubuntu.upstream.yaml

Imported here: https://packagecloud.io/dirk-thomas/colcon
- colcon-alias 0.1.1
- colcon-core 0.17.0
- colcon-ros 0.5.0

Update to the latest colcon releases

---

config/ignition_citadel_gazebo11_ubuntu_focal.yaml

Fix ign-rendering3 version in ignition_citadel_gazebo11_ubuntu_focal
